CREATE TABLE IF NOT EXISTS ie_vocab (
    id SERIAL PRIMARY KEY,
    vocab VARCHAR NOT NULL,
    vocab_list_id INTEGER NOT NULL,
    prons JSON NOT NULL,
    defs JSON NOT NULL,
    props JSON NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
