CREATE TABLE IF NOT EXISTS ie_vocab_list (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    article_id INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
